from .user import User
from .vehicle import Vehicle
from .driver import Driver
from .shipment import Shipment
from .trip import Trip
from .gps_tracking import GPSTracking
from .maintenance import VehicleMaintenance
from .fuel_record import FuelRecord
from .notification import Notification
from .attendance import Attendance
from .email_verification import EmailVerification