"""add_fuel_mileage_refill_date_and_trip_route_type

Revision ID: ce7705bca6c8
Revises: 477951ad2918
Create Date: 2026-08-24 15:40:53.730024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7705bca6c8'
down_revision: Union[str, Sequence[str], None] = '477951ad2918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_records', sa.Column('fuel_amount', sa.Float(), nullable=False))
    op.add_column('fuel_records', sa.Column('fuel_cost', sa.Float(), nullable=False))
    op.add_column('fuel_records', sa.Column('mileage', sa.Float(), nullable=True))
    op.add_column('fuel_records', sa.Column('refill_date', sa.Date(), nullable=True))
    op.add_column('fuel_records', sa.Column('notes', sa.String(length=255), nullable=True))
    op.drop_column('fuel_records', 'amount')
    op.drop_column('fuel_records', 'cost')
    op.add_column('trips', sa.Column('route_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'route_type')
    op.add_column('fuel_records', sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('fuel_records', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('fuel_records', 'notes')
    op.drop_column('fuel_records', 'refill_date')
    op.drop_column('fuel_records', 'mileage')
    op.drop_column('fuel_records', 'fuel_cost')
    op.drop_column('fuel_records', 'fuel_amount')
    # ### end Alembic commands ###
