"""add route fields to trips

Revision ID: 45fce1d17fd7
Revises: cc54b4823c34
Create Date: 2026-08-06 20:58:09.890732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45fce1d17fd7'
down_revision: Union[str, Sequence[str], None] = 'cc54b4823c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types first
    op.execute("CREATE TYPE shipmentstatus AS ENUM ('Created', 'Assigned', 'InTransit', 'Delayed', 'Delivered', 'Cancelled')")
    op.execute("CREATE TYPE tripstatus AS ENUM ('Scheduled', 'InTransit', 'Completed', 'Cancelled')")
    op.execute("CREATE TYPE fueltype AS ENUM ('Petrol', 'Diesel', 'Electric', 'CNG')")
    op.execute("CREATE TYPE vehiclestatus AS ENUM ('Available', 'Assigned', 'Maintenance', 'InTransit')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gps_tracking', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('gps_tracking', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('gps_tracking', 'longitude',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('gps_tracking', 'speed',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('shipments', 'source',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('shipments', 'destination',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('shipments', 'customer_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('shipments', 'shipment_weight',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Created', 'Assigned', 'InTransit', 'Delayed', 'Delivered', 'Cancelled', name='shipmentstatus'),
               nullable=False,
               postgresql_using="status::shipmentstatus")
    op.drop_constraint(op.f('shipments_driver_id_fkey'), 'shipments', type_='foreignkey')
    op.execute("UPDATE shipments SET driver_id = (SELECT user_id FROM drivers WHERE drivers.driver_id = shipments.driver_id) WHERE driver_id IS NOT NULL")
    op.create_foreign_key(None, 'shipments', 'users', ['driver_id'], ['user_id'])
    op.drop_column('shipments', 'expected_delivery_time')
    op.drop_column('shipments', 'updated_at')
    op.add_column('trips', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('eta', sa.DateTime(), nullable=True))
    op.add_column('trips', sa.Column('route_type', sa.String(length=50), nullable=True))
    op.add_column('trips', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('trips', 'shipment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('trips', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('trips', 'driver_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('trips', 'start_location',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('trips', 'destination',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('trips', 'distance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('trips', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Scheduled', 'InTransit', 'Completed', 'Cancelled', name='tripstatus'),
               existing_nullable=True,
               postgresql_using="status::tripstatus")
    op.drop_constraint(op.f('trips_driver_id_fkey'), 'trips', type_='foreignkey')
    op.execute("UPDATE trips SET driver_id = (SELECT user_id FROM drivers WHERE drivers.driver_id = trips.driver_id) WHERE driver_id IS NOT NULL")
    op.create_foreign_key(None, 'trips', 'users', ['driver_id'], ['user_id'])
    op.add_column('vehicles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('vehicles', 'registration_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('vehicles', 'fuel_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Petrol', 'Diesel', 'Electric', 'CNG', name='fueltype'),
               existing_nullable=True,
               postgresql_using="fuel_type::fueltype")
    op.alter_column('vehicles', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Available', 'Assigned', 'Maintenance', 'InTransit', name='vehiclestatus'),
               existing_nullable=True,
               postgresql_using="status::vehiclestatus")
    op.drop_constraint(op.f('vehicles_assigned_driver_fkey'), 'vehicles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('vehicles_assigned_driver_fkey'), 'vehicles', 'drivers', ['assigned_driver'], ['driver_id'])
    op.alter_column('vehicles', 'status',
               existing_type=sa.Enum('Available', 'Assigned', 'Maintenance', 'InTransit', name='vehiclestatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('vehicles', 'fuel_type',
               existing_type=sa.Enum('Petrol', 'Diesel', 'Electric', 'CNG', name='fueltype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('vehicles', 'registration_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('vehicles', 'updated_at')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key(op.f('trips_driver_id_fkey'), 'trips', 'drivers', ['driver_id'], ['driver_id'])
    op.alter_column('trips', 'status',
               existing_type=sa.Enum('Scheduled', 'InTransit', 'Completed', 'Cancelled', name='tripstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('trips', 'distance',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('trips', 'destination',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('trips', 'start_location',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('trips', 'driver_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('trips', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('trips', 'shipment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('trips', 'created_at')
    op.drop_column('trips', 'route_type')
    op.drop_column('trips', 'eta')
    op.drop_column('trips', 'duration')
    op.add_column('shipments', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('expected_delivery_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.create_foreign_key(op.f('shipments_driver_id_fkey'), 'shipments', 'drivers', ['driver_id'], ['driver_id'])
    op.alter_column('shipments', 'status',
               existing_type=sa.Enum('Created', 'Assigned', 'InTransit', 'Delayed', 'Delivered', 'Cancelled', name='shipmentstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('shipments', 'shipment_weight',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('shipments', 'customer_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('shipments', 'destination',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('shipments', 'source',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('gps_tracking', 'speed',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('gps_tracking', 'longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=6),
               nullable=True)
    op.alter_column('gps_tracking', 'latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=6),
               nullable=True)
    op.alter_column('gps_tracking', 'vehicle_id',
               existing_type=sa.UUID(),
               nullable=True)
    
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS shipmentstatus")
    op.execute("DROP TYPE IF EXISTS tripstatus")
    op.execute("DROP TYPE IF EXISTS fueltype")
    op.execute("DROP TYPE IF EXISTS vehiclestatus")
    # ### end Alembic commands ###
